# action.yaml
name: "Sphinx to Coda Action"
description: "Ideally this should take an Intersphinx Item and Upload an Index of that Documentation to Coda.io"
inputs:
  uribase:
    description: "The base URL of the project. Somethin like http://example.com/docs/"
    required: true
  intersphinx_file:
    description: 'The location of the objects.inv file or path'
    default: "build/html/objects.inv"
  docID:
    description: "The DocID Where the resulting documentation should go."
    required: true
  pageID:
    # Override to Specific Page
    description: "The Specific PageID that will get overwritten."
    required: false
    default: 'false'
  staticParentId:
    description: "Only look at pages with this pageID as it's Parent"
    required: false
    default: 'false'
  coda_token:
    description: "Coda API Token"
    required: true
  template:
    description: "Jinja Template that get's built"
    default: "./src/template.html.jinja"
  s3profile:
    description: "AWS Profile to use for S3 rewrites, uses the default profile if not set"
    required: false
    default: "default"
  s3bucket:
    description: "AWS Bucket to use for S3 rewrites if unset images won't be rewritten for upload"
    required: false
    default: "none"
  s3prefix:
    description: "AWS Object Path Prefix to use for S3 Rewrites. By default it's blank"
    required: false
    default: ""
  dodelete:
    description: "When writing a path of pages, delete unmatched pages in the target document. (yes/no) default yes"
    required: false
    default: "yes"
#outputs:
#  num_squared:
#    description: 'Square of the input'
#    # need to specify the extra `value` field for `composite` actions
#    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - uses: getsentry/action-setup-venv@v2.1.1
      id: venv
      with:
        python-version: '3.11'
        cache-dependency-path: |
          ${{ github.action_path }}/requirements.txt
        venv-dir: ${{ github.action_path }}/venv
        install-cmd: pip install -r ${{ github.action_path }}/requirements.txt

    - name: parse_and_upload.py
      id: pau
      run: source venv/bin/activate; ./src/parse_and_upload.py -vvv
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        SPHINX_BASE_URI: ${{ inputs.uribase }}
        OBJECTS_FILE: ${{ github.workspace }}/${{ inputs.intersphinx_file }}
        DOCID: ${{ inputs.docID }}
        PAGEID: ${{ inputs.pageID }}
        CODA_TOKEN: ${{ inputs.coda_token }}
        TEMPLATE: ${{ inputs.template }}
        STATICPID: ${{ inputs.staticParentId }}
        S3PROFILE: ${{ inputs.s3profile }}
        S3BUCKET: ${{ inputs.s3bucket }}
        S3PREFIX: ${{ inputs.s3prefix }}
        DODEL: ${{ inputs.dodelete }}
